open Interface

let header = {|(* This file has been generated by coq-bindgen. *)

From Base Require Import Prelude.
From FreeSpec.Core Require Import All.|}

let print_coq_type (t : type_desc) =
  let name = Ident.name t.name in
  match t.coq_model with
  | Some ident ->
    print_string @@ "Definition " ^ name ^ " : Type :=\n";
    print_string @@ "  " ^ ident ^ "."
  | None ->
    print_string @@ "Axiom " ^ name ^ " : Type."

let print_coq_types i =
  List.iter print_coq_type i.types

let print_coq_function modname (t : function_desc) =
  let name = Ident.name t.name in
  begin
    match t.coq_model with
    | Some ident ->
      print_string @@ "Definition " ^ name ^ " : ?? :=\n";
      print_string @@ "  " ^ ident ^ ".\n"
    | None ->
      print_string @@ "Axiom " ^ name ^ " : ??.\n";
  end;
  print_string @@ "Extract Constant " ^ name ^ " => ";
  print_string @@ "\"" ^ String.concat "." modname ^ "." ^ name ^ "\".\n"

let print_coq_primitive iname p =
  let pname = String.capitalize_ascii @@ Ident.name p.name in
  print_string @@ "\n| " ^ pname ^ " : " ^ iname ^ " ??"

let print_coq_primitives i =
  let rec last = function
    | [x] -> x
    | _ :: rst -> last rst
    | _ -> assert false in
  let name = String.uppercase_ascii (last i.module_path) in
  print_string @@ "Inductive " ^ name ^ " : interface :=";
  List.iter (print_coq_primitive name) i.primitives;
  print_string "."

let print_coq_functions i =
  List.iter (print_coq_function i.module_path) i.functions

let print_coq_interface i =
  print_string header;
  print_newline ();
  print_coq_types i;
  print_newline ();
  print_coq_functions i;
  print_newline ();
  print_coq_primitives i
